PUT http://localhost:3003/api/blogs/68a5f581cd6796e1bc0aaaf1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhc3F1ZXoiLCJpZCI6IjY4YTYyYmJkMzk2YTE1MjAwMGI4MDgwZiIsImlhdCI6MTc1NjQ3NjUyMiwiZXhwIjoxNzU2NDgwMTIyfQ.r0OdPwUXXVs5eOakw22azOi_w8kaLEEU9dG5Oko4obg
