POST http://localhost:3003/api/blogs
Content-Type: application/json 

{
    "title": "Advance in small steps",
    "author": "Chefi",
    "url": "https://................",
    "likes": 19,
    "userId": "68a0cc4ba22b3f8c084430c6"
}