DELETE http://localhost:3003/api/blogs/68a5f581cd6796e1bc0aaaf1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1henp1Y28iLCJpZCI6IjY4YTIyNWU3YjVkNmRlMDYxN2M1NDllMSIsImlhdCI6MTc1NTcwNjcyNiwiZXhwIjoxNzU1NzEwMzI2fQ.KZyCSMSZvHuHXxmZ2nmEu89otcwTVBj5c4lqk9Rgw0k