POST http://localhost:3003/api/blogs
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlF1ZXJvbCIsImlkIjoiNjhlMDczMzg3ZmY5ODdiNTc2MDZiOWM5IiwiaWF0IjoxNzU5NTQwNDI0LCJleHAiOjE3NTk1NDQwMjR9.wvYYIcsYpC_dsf2bn5Mt-Hams7pyZgY9NQEqu_Q3KRs

{
        "title": "Benjamin and Joaco, a great friendship",
        "author": "Miqueas",
        "url": "https://inventedUrl.com",
        "likes": 180
}
